name:  CD

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      lpath: ${{ steps.filter.outputs.lpath }}
      alias: ${{ steps.filter.outputs.alias }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        # filters: .github/file-filters.yaml
        filters: |
          lpath:
            - 'rym-lpath/**'
          alias:
            - 'rym-alias/**'
  rym-alias:
    needs: changes
    if: ${{ needs.changes.outputs.alias == 'true' || startsWith(github.event.head_commit.message, 'build') }}
    uses: ./.github/workflows/publish-to-pypi.yaml
    with:
      target: rym-alias
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  rym-lpath:
    needs: changes
    if: ${{ needs.changes.outputs.lpath == 'true' || startsWith(github.event.head_commit.message, 'build') }}
    uses: ./.github/workflows/publish-to-pypi.yaml
    with:
      target: rym-lpath
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
