name:  CI/CD

on: push

jobs:
  change-matrix:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      lpath: ${{ steps.filter.outputs.lpath }}
      alias: ${{ steps.filter.outputs.alias }}
      token: ${{ steps.filter.outputs.token }}
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
      with:
        # This may save additional git fetch roundtrip if
        # merge-base is found within latest 20 commits
        fetch-depth: 20
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          rym-lpath:
            - 'rym-lpath/**'
          rym-alias:
            - 'rym-alias/**'
          rym-token:
            - 'rym-token/**'
  python-package:
    name: "${{ matrix.package }}"
    needs: change-matrix
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        package: ${{ fromJSON(needs.change-matrix.outputs.packages) }}
    uses: ./.github/workflows/py-pkg.yaml
    with:
      package: ${{ matrix.package }}
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
