name:  CI/CD

on: push

jobs:
  change-matrix:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v3
      with:
        # This may save additional git fetch roundtrip if
        # merge-base is found within latest 20 commits
        fetch-depth: 20
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.base_ref }}
        filters: |
          rym-lpath:
            - 'rym-lpath/**'
          rym-alias:
            - 'rym-alias/**'
          rym-token:
            - 'rym-token/**'
  python-package-change:
    name: "${{ matrix.package }}"
    if: ${{ needs.change-matrix.outputs.packages != '[]' && needs.change-matrix.outputs.packages != '' }}
    needs: change-matrix
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        package: ${{ fromJSON(needs.change-matrix.outputs.packages) }}
    uses: ./.github/workflows/py-pkg.yaml
    with:
      package: ${{ matrix.package }}
      publish_to_pypi_real: false
      publish_to_pypi_test: true
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  tag-matrix:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.get-package.outputs.package }}
    steps:
      - id: get-package
        if: ${{ startsWith(github.ref, 'refs/tags/rym-') }}
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          PKGS="[\"${TAG_NAME%%-v[0-9]*}\"]"
          echo "packages: ${PKGS}"
          echo "packages=${PKGS}" >> $GITHUB_OUTPUT
  python-package-tag:
    name: "${{ matrix.package }}"
    if: ${{ needs.tag-matrix.outputs.packages != '[]' && needs.tag-matrix.outputs.packages != '' }}
    needs: tag-matrix
    strategy:
      # Parse JSON array containing names of all filters matching any of changed files
      matrix:
        package: ${{ fromJSON(needs.tag-matrix.outputs.packages) }}
    uses: ./.github/workflows/py-pkg.yaml
    with:
      package: ${{ matrix.package }}
      publish_to_pypi_real: true
      publish_to_pypi_test: false
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}