name:  CI

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      lpath: ${{ steps.filter.outputs.lpath }}
      alias: ${{ steps.filter.outputs.alias }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # filters: .github/file-filters.yaml
        filters: |
          lpath:
            - 'mjb-lpath/**'
          alias:
            - 'mjb-alias/**'
  mjb-alias:
    needs: changes
    if: ${{ needs.changes.outputs.alias == 'true' }}
    uses: ./.github/workflows/test-pdm.yaml
    with:
      target: mjb-alias
  mjb-lpath:
    needs: changes
    if: ${{ needs.changes.outputs.lpath == 'true' }}
    uses: ./.github/workflows/test-pdm.yaml
    with:
      target: mjb-lpath
