name:  CI

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  changed-dirs:
    outputs:
      dirnames: ${{ steps.changed-files-dirnames.outputs.all_changed_and_modified_files }}
    steps:
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          json: "true"
          files: |
            mjb-*/**
  test:
    runs-on: ${{ matrix.os }}
    needs: changed-files
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']
        os: [ubuntu-latest]
        pkg: ${{ needs.changed-dirs.outputs.dirnames }}
        # os: [ubuntu-latest, macOS-latest, windows-latest]
    defaults:
      run:
        working-directory: ./${{ matrix.pkg }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: '${{ matrix.pkg }}/pdm.lock'
      - name: Install dependencies
        run: |
          pdm sync --dev
      - name: Run Tests
        run: |
          pdm run -v pytest

