name: Python Package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true
      PYPI_API_TOKEN:
        required: true

jobs:
  test:
    uses: ./.github/workflows/test-pdm.yaml
    with:
      target: ${{ inputs.package }}
  build-publish:
    needs: [test]
    uses: ./.github/workflows/publish-to-pypi.yaml
    with:
      target: ${{ inputs.package }}
    secrets: inherit
      # TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      # PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}