name:  CI

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./${{ inputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 50
          fetch-tags: true
      - name: Get tags
        run: git fetch --tags origin
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: '${{ inputs.target }}/pdm.lock'
      - name: Install dependencies
        run: |
          git fetch --tags origin
          pdm sync --dev -v
      - name: Test
        run: |
          pdm run -v pytest
